# Generated by Django 4.2.1 on 2023-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_linksuser_email_alter_linksuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
