# Generated by Django 4.2.1 on 2023-05-26 11:29

from django.db import migrations
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_linksuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='linksuser',
            managers=[
                ('objects', myapp.models.LinksUserManager()),
            ],
        ),
    ]
